# 使用 Node.js 镜像构建前端应用
FROM node:20

# 设置工作目录
WORKDIR /appClient

# 复制 package.json 和 package-lock.json
COPY package*.json ./
# 安装依赖
RUN npm install

# 复制前端项目源代码
COPY dist /appClient/dist

# 构建前端应用
RUN npm run build

# 使用 Nginx 提供前端应用
FROM nginx

# 将构建好的文件从前一个镜像复制到 Nginx 的默认目录
COPY dist /usr/share/nginx/html

# 将自定义 Nginx 配置文件（如果有）复制到容器中
COPY nginx.conf /etc/nginx/nginx.conf

# 暴露 Nginx 默认的端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]
