version: '3'

services:
  frontend:
    image: client-image
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network      

  backend:
    image: server-image
    container_name: backend
    ports:
      - "8888:8888"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tp_education
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      - db
    networks:
      - app-network    

  db:
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tp_education
      MYSQL_USER: my_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  python-thought:
    image: thought
    container_name: python-thought
    ports:
      - "8890:8890"

  python-assess:
    image: assess
    container_name: python-assess
    ports:
      - "8891:8891"

volumes:
  mysql_data:

networks:
  app-network:
