server:
  port: 8888

#logging logback
#Todo

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

system:
  security-ignore-urls:
    - /api/student/user/register
    - /api/teacher/user/register
    - /api/admin/user/register
    - /api/
  pwd-key:
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQClwwxhJKwStDnu7c0yCRkwTW2VKuLWwyVtFC6Zx9bYdF1qwqSP26CkDwaF6GHayIvv9b8BHlAaQH4SLIPzir062yzNukqspmthUw4gPJhbx1AQrWRoQJSv3/1Sk+tWyJRHXSiCZJZ3216LDhtx42LQ0HItDP8U9BLtsxA+5LEZzQIDAQAB
    private-key: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAKXDDGEkrBK0Oe7tzTIJGTBNbZUq4tbDJW0ULpnH1th0XWrCpI/boKQPBoXoYdrIi+/1vwEeUBpAfhIsg/OKvTrbLM26Sqyma2FTDiA8mFvHUBCtZGhAlK/f/VKT61bIlEddKIJklnfbXosOG3HjYtDQci0M/xT0Eu2zED7ksRnNAgMBAAECgYEAlCuz5yn2volnt9HNuEo1v92WdN5vAnZSAB0oQsJFpBrwXjw7CXTTNZNQy2YcAot9uzO6Vu+Xvr+jce9ky9BasM7ehz0gnwJWAO79IqUnmu3RRq7HllDwp72qysXIypJZCF4HX5jAzUGlNzlTSUb1H4LtavKc6a//YqPfQ0jTLsECQQDZuGKGAYq6rBCX0+T8qlQpCPc41wsl4Gi9lLD21ks9PMx44JdhsUrqLWItZiGynDzq1LJ3M1hr3gbSsPQcI9HJAkEAwugDFCiRLOqOBRRGlYbzgGdmXbR4SrMNIpcFTFhU+MsEqaMueVPiNtRSIK6W8pS28ZN0aiZDTBAT84fOIENp5QJBAJaVgQ9OYbVa7N8WH3riE/ONz+/wTDWWUNtOzFbtQHzKYGH6dLmM9lOhsBXWXdg7V6bUFdt8F9wDZJS07yHHZIECQG4rHrJiS80Lt8L/NvaGFVVbHO2SePwgQShwHLqOo1kNyFDqv/YsiA1d7h4zEXeEv/PE2WS2xAtWezCIbualtFECQQDPUkYhs3vZoZgsltdeFnv/WoXaXNRIzunMTmksIlh8JP7C1xQHrwdCpUkffgSVphxGJGHkxooMpki7oTC1Mdjx
  jwt:
    secret-key: V3Sdiyqdwmm9mGSU9akX2UYLNzeeCzUbbsam7/Ot+sQ=
    expiration: 7
  qn:
    url: http://sg8dboiyc.hd-bkt.clouddn.com
    bucket: cs-education-platform
    access-key: oJOFdOBRRkkYi7ssuvB17PpRXrXzZjU46-eOsnbd
    secret-key: 5pp0Y1WoB1118fiQWDpnh6MJGYtKoNyd6M_zIGPI
  judge0:
    create:
      url: https://judge0-extra-ce.p.rapidapi.com/submissions?base64_encoded=true&wait=false&fields=*
      X-RapidAPI-Key: 30aec1aee9msh3853a2407d66699p112776jsn580b58a4ab68
      X-RapidAPI-Host: judge0-extra-ce.p.rapidapi.com
    get:
      url-front: https://judge0-extra-ce.p.rapidapi.com/submissions/
      url-back: ?base64_encoded=true&wait=false&fields=*
      X-RapidAPI-Key: 30aec1aee9msh3853a2407d66699p112776jsn580b58a4ab68
      X-RapidAPI-Host: judge0-extra-ce.p.rapidapi.com
    status:
      url: https://judge0-extra-ce.p.rapidapi.com/statuses
      X-RapidAPI-Key: 30aec1aee9msh3853a2407d66699p112776jsn580b58a4ab68
      X-RapidAPI-Host: judge0-extra-ce.p.rapidapi.com
    lang:
      url: https://judge0-extra-ce.p.rapidapi.com/languages
      X-RapidAPI-Key: 30aec1aee9msh3853a2407d66699p112776jsn580b58a4ab68
      X-RapidAPI-Host: judge0-extra-ce.p.rapidapi.com
  websocket:
    chain-url: ws://localhost:8890
    assess-url: ws://localhost:8891

spring:
  #runningtime environment
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB
      max-request-size: 300MB

ok:
  http:
    connect-timeout: 180
    read-timeout: 180
    write-timeout: 180
    # 连接池中整体的空闲连接的最大数量
    max-idle-connections: 200
    # 连接空闲时间最多为 300 秒
    keep-alive-duration: 300

spark:
  ai-img:
    host-url: https://spark-api.cn-huabei-1.xf-yun.com/v2.1/tti
    app-id: 5e04969c
    api-secret: Y2JiZThhYjI2ZmYzODI1MDMwZmQyZTgy
    api-key: f318d6bf3b1b6051b787e1752ed17532
  ai-rewrite:
    request-url: https://api.xf-yun.com/v1/private/se3acbe7f
    app-id: 5e04969c
    api-secret: Y2JiZThhYjI2ZmYzODI1MDMwZmQyZTgy
    api-key: f318d6bf3b1b6051b787e1752ed17532
  ai-chat-doc:
    upload-url: https://chatdoc.xfyun.cn/openapi/v1/file/upload
    chat-url: wss://chatdoc.xfyun.cn/openapi/chat
    summary-start-url: https://chatdoc.xfyun.cn/openapi/v1/file/summary/start
    summary-query-url: https://chatdoc.xfyun.cn/openapi/v1/file/summary/query
    app-id: 5e04969c
    secret: Y2JiZThhYjI2ZmYzODI1MDMwZmQyZTgy
  ai-ppt:
    base-url: https://zwapi.xfyun.cn
    app-id: 5e04969c
    secret: Y2JiZThhYjI2ZmYzODI1MDMwZmQyZTgy


