server:
  port: 8888

#logging logback
#Todo

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  #runningtime environment
  profiles:
    active: dev